version: "3"
services:
  telegraf:
    image: seraf/rpi-greenhouse-telegraf
    restart: always
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    hostname: serre-telegraf
    network_mode: "host"
    volumes:
     - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
     - ./checks:/checks:ro
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - /sys:/rootfs/sys:ro
     - /proc:/rootfs/proc:ro
     - /etc:/rootfs/etc:ro
  flower-power:
    image: seraf/rpi-flower-power
    restart: always
    environment:
      REFRESH_INTERVAL: 1h
    hostname: serre-flower-power
    network_mode: "host"
    volumes:
     - ./flower-power/credentials.json:/home/pi/node-flower-bridge/credentials.json:ro
