version: "3"
services:
  telegraf:
    image: seraf/rpi-greenhouse-telegraf:latest
    restart: always
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    hostname: serre-telegraf
    privileged: true
    network_mode: "host"
    volumes:
     - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
     - ./checks:/checks:ro
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - /sys:/rootfs/sys:ro
     - /proc:/rootfs/proc:ro
     - /etc:/rootfs/etc:ro
    logging:
      options:
        max-size: "2m"
        max-file: "10"
