version: '3'
services:
  nginx-web:
    image: nginx
    restart: always
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx-web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data-nginx/conf.d:/etc/nginx/conf.d
      - ./data-nginx/vhost.d:/etc/nginx/vhost.d
      - ./data-nginx/html:/usr/share/nginx/html
      - ./data-nginx/certs:/etc/nginx/certs:rw
    logging:
      options:
        max-size: "4m"
        max-file: "10"

  nginx-gen:
    restart: always
    image: jwilder/docker-gen
    command: -notify-sighup nginx-web -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data-nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - ./data-nginx/conf.d:/etc/nginx/conf.d
      - ./data-nginx/vhost.d:/etc/nginx/vhost.d
      - ./data-nginx/html:/usr/share/nginx/html
      - ./data-nginx/certs:/etc/nginx/certs:rw
    logging:
      options:
        max-size: "2m"
        max-file: "10"

  nginx-letsencrypt:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data-nginx/conf.d:/etc/nginx/conf.d
      - ./data-nginx/vhost.d:/etc/nginx/vhost.d
      - ./data-nginx/html:/usr/share/nginx/html
      - ./data-nginx/certs:/etc/nginx/certs:rw
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
      - NGINX_PROXY_CONTAINER=nginx-webproxy
    logging:
      options:
        max-size: "2m"
        max-file: "10"

networks:
  default:
    external:
      name: nginx-proxy
