version: '3'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    volumes:
      - /home/seraf/docker-data/influxdb/data:/var/lib/influxdb
      - /home/seraf/nas/backup:/backup
    restart: always
    logging:
      options:
        max-size: "2m"
        max-file: "10"

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    links:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    restart: always
    logging:
      options:
        max-size: "2m"
        max-file: "10"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    links:
      - influxdb
    volumes:
      - /home/seraf/docker-data/grafana/data:/var/lib/grafana
    restart: always
    logging:
      options:
        max-size: "2m"
        max-file: "10"
    environment:
      - VIRTUAL_HOST=metrics.aquaponie.syx.fr
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=metrics.aquaponie.syx.fr
      - LETSENCRYPT_EMAIL=nephilim.seraphin@gmail.com

networks:
  default:
    external:
      name: nginx-proxy
