influxdb:
  image: influxdb:latest
  container_name: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
  env_file:
    - 'env.influxdb'
  volumes:
    - /home/seraf/docker-data/influxdb/data:/var/lib/influxdb
    - /home/seraf/nas/backup:/backup
  restart: always

telegraf:
  image: telegraf:latest
  container_name: telegraf
  links:
    - influxdb
  volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
  restart: always

grafana:
  image: grafana/grafana:latest
  container_name: grafana
  ports:
    - "3000:3000"
  env_file:
    - 'env.grafana'
  links:
    - influxdb
  restart: always

nginx:
  image: nginx
  restart: always
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
  container_name: nginx
  links:
    - grafana
  ports:
    - 80:80
